# Generated by Django 5.2.4 on 2025-07-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                ("descripcion", models.TextField(verbose_name="descripcion")),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="precio"
                    ),
                ),
                (
                    "stock",
                    models.PositiveBigIntegerField(default=0, verbose_name="stock"),
                ),
                (
                    "creado",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "actualizado",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
            ],
        ),
    ]
