# Generated by Django 5.2.4 on 2025-07-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
